name: Build relase for different JDK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8 and upload jar
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: |
          ./gradlew createRunnableScript
      - uses: actions/upload-artifact@v2
        with:
          name: btcli4j-all-JDK8
          path: build/libs/btcli4j-all.jar
      - name: Set up JDK 11 and upload jar
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: |
          ./gradlew createRunnableScript
      - uses: actions/upload-artifact@v2
        with:
          name: btcli4j-all-JDK11
          path: build/libs/btcli4j-all.jar
      - name: Set up JDK 14 and upload jar
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: |
          ./gradlew createRunnableScript
      - uses: actions/upload-artifact@v2
        with:
          name: btcli4j-all-JDK14
          path: build/libs/btcli4j-all.jar